DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:388 POST http://127.0.0.1:54848/session/36435e82bb7378286bf5dfb1e270447b/window/maximize {}
DEBUG    urllib3.connectionpool:connectionpool.py:243 Resetting dropped connection: 127.0.0.1
DEBUG    urllib3.util.retry:retry.py:390 Incremented Retry for (url='/session/36435e82bb7378286bf5dfb1e270447b/window/maximize'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING  urllib3.connectionpool:connectionpool.py:663 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015A5125B0C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/36435e82bb7378286bf5dfb1e270447b/window/maximize
DEBUG    urllib3.connectionpool:connectionpool.py:208 Starting new HTTP connection (2): 127.0.0.1
DEBUG    urllib3.util.retry:retry.py:390 Incremented Retry for (url='/session/36435e82bb7378286bf5dfb1e270447b/window/maximize'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING  urllib3.connectionpool:connectionpool.py:663 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015A51327308>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/36435e82bb7378286bf5dfb1e270447b/window/maximize
DEBUG    urllib3.connectionpool:connectionpool.py:208 Starting new HTTP connection (3): 127.0.0.1
DEBUG    urllib3.util.retry:retry.py:390 Incremented Retry for (url='/session/36435e82bb7378286bf5dfb1e270447b/window/maximize'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING  urllib3.connectionpool:connectionpool.py:663 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015A5132B708>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/36435e82bb7378286bf5dfb1e270447b/window/maximize
DEBUG    urllib3.connectionpool:connectionpool.py:208 Starting new HTTP connection (4): 127.0.0.1